server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: notsecret
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  jmx:
    enabled: false
  profiles:
    active: default
  datasource:
      url: jdbc:h2:mem:aesop;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      sql-script-encoding: UTF-8
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: true
